import assert from 'node:assert/strict';
import test from 'node:test';

import { createEmptyPlannerSeedData } from '../lib/planner-defaults';
import {
  buildPlannerDialogState,
  buildPlannerDocumentState,
  buildPlannerShellState,
  buildPlannerThreadState,
} from './planner-page-state-slices';

test('planner page slice builders preserve explicit slice boundaries', () => {
  const shell = buildPlannerShellState({
    plannerMode: 'series',
    displayTitle: '夜航者',
    brief: 'brief',
    runtimeEnabled: true,
    openAgentDebug: () => undefined,
    backToExplore: () => undefined,
    activeEpisodeId: 'episode-1',
    setActiveEpisodeId: () => undefined,
    plannerEpisodes: [],
    activeEpisodeNumber: 1,
    activeEpisodeTitle: '第1集',
    fallbackEpisodeTitle: '夜航者',
    saveState: { status: 'idle', message: '' },
    latestExecutionMode: 'live',
    activeDebugApplySource: null,
    historyMenuOpen: false,
    historyVersions: [],
    historyActiveVersionId: null,
    openDebugRun: () => undefined,
    toggleHistoryMenu: () => undefined,
    handleSelectHistoryVersion: async () => undefined,
  });
  const thread = buildPlannerThreadState({
    studio: { brandName: 'AIV', assistantName: 'Seko', project: {} as never, episodes: [], planner: { submittedRequirement: '', pointCost: 0, messages: [] }, creation: { points: 0 } },
    usingRuntimePlanner: true,
    messages: [],
    requirement: '写一个悬疑短剧',
    setRequirement: () => undefined,
    outlineConfirmed: false,
    runtimeActiveOutline: null,
    runtimeActiveRefinement: null,
    plannerSubmitting: false,
    serverPlannerText: '',
    refinementDetailSteps: [],
    activeVersion: null,
    activeDebugApplySource: null,
    notice: null,
    openDebugRun: () => undefined,
    handleComposerSubmit: () => undefined,
    handleConfirmOutline: () => undefined,
  });
  const document = buildPlannerDocumentState({
    hasDisplayVersion: true,
    runtimeActiveOutline: null,
    runtimeActiveRefinement: null,
    displayVersionStatus: 'ready',
    displayVersionProgress: null,
    displaySections: { summary: true },
    plannerDoc: createEmptyPlannerSeedData({
      brandName: 'AIV',
      assistantName: 'Seko',
      project: {
        id: 'project-1',
        title: '夜航者',
        brief: 'brief',
        contentMode: 'series',
        executionMode: 'auto',
        aspectRatio: '16:9',
        status: 'planning',
      },
      episodes: [],
      planner: { submittedRequirement: '', pointCost: 0, messages: [] },
      creation: { points: 0 },
    }),
    activeStyle: { name: '韩漫二次元', tone: '高对比' },
    mediaCardStyle: {},
    displaySubjectCards: [],
    openSubjectAdjustDialog: () => undefined,
    displaySceneCards: [],
    openSceneAdjustDialog: () => undefined,
    displayScriptActs: [],
    plannerSubmitting: false,
    runtimeEnabled: true,
    editingShot: null,
    shotDraft: null,
    openShotInlineEditor: () => undefined,
    openShotDeleteDialog: () => undefined,
    rerunActAdjust: async () => undefined,
    setShotDraft: () => undefined,
    rerunShotAdjust: async () => undefined,
    generateShotImage: async () => undefined,
    cancelShotInlineEditor: () => undefined,
    applyShotInlineEditor: async () => undefined,
    shotPromptPreview: null,
    shotPromptPreviewLoading: false,
    shotPromptPreviewError: null,
    selectedStoryboardModel: null,
    storyboardModelId: 'seedream-4',
    setStoryboardModelId: () => undefined,
    aspectRatio: '16:9',
    setAspectRatio: () => undefined,
    startCreation: async () => undefined,
    creationActionLabel: '开始创作',
    creationActionDisabled: false,
    shotTitleById: {},
  });
  const dialogs = buildPlannerDialogState({
    plannerSubmitting: false,
    runtimeEnabled: true,
    assetUploadPending: null,
    booting: false,
    bootProgress: 0,
    remainingPoints: 100,
    subjectDialogCardId: null,
    activeSubjectCard: null,
    subjectImageDraft: '',
    subjectNameDraft: '',
    subjectPromptDraft: '',
    subjectAdjustMode: 'ai',
    activeSubjectAssetLabel: '',
    subjectAssetThumbs: [],
    subjectAssetDraftId: null,
    subjectRecommendations: [],
    subjectRecommendationsLoading: false,
    subjectUploadInputRef: { current: null },
    closeSubjectAdjustDialog: () => undefined,
    setSubjectImageDraft: () => undefined,
    setSubjectAssetDraftId: () => undefined,
    setSubjectPromptDraft: () => undefined,
    setSubjectAdjustMode: () => undefined,
    applySubjectRecommendation: () => undefined,
    generateSubjectImage: async () => undefined,
    rerunSubjectAdjust: async () => undefined,
    applySubjectAdjust: async () => undefined,
    handleSubjectUpload: async () => undefined,
    sceneDialogCardId: null,
    activeSceneCard: null,
    sceneImageDraft: '',
    sceneNameDraft: '',
    scenePromptDraft: '',
    sceneAdjustMode: 'ai',
    activeSceneAssetLabel: '',
    sceneAssetThumbs: [],
    sceneAssetDraftId: null,
    sceneRecommendations: [],
    sceneRecommendationsLoading: false,
    sceneUploadInputRef: { current: null },
    closeSceneAdjustDialog: () => undefined,
    setSceneImageDraft: () => undefined,
    setSceneAssetDraftId: () => undefined,
    setScenePromptDraft: () => undefined,
    setSceneAdjustMode: () => undefined,
    applySceneRecommendation: () => undefined,
    generateSceneImage: async () => undefined,
    rerunSceneAdjust: async () => undefined,
    applySceneAdjust: async () => undefined,
    handleSceneUpload: async () => undefined,
    shotDeleteDialog: null,
    deletingShot: null,
    closeShotDeleteDialog: () => undefined,
    confirmDeleteShot: async () => undefined,
  });

  assert.equal(shell.activeEpisodeId, 'episode-1');
  assert.equal(thread.requirement, '写一个悬疑短剧');
  assert.equal(document.creationActionLabel, '开始创作');
  assert.equal(dialogs.remainingPoints, 100);
});
