'use client';
import { useRouter } from 'next/navigation';

import type { ApiPlannerWorkspace, PlannerRuntimeApiContext } from '../lib/planner-api';
import type { PlannerPageData } from '../lib/planner-page-data';
import { mapWorkspaceMessagesToThread, nextLocalId } from '../lib/planner-page-helpers';
import type { PlannerStructuredDoc } from '../lib/planner-structured-doc';
import { usePlannerDocumentPersistence } from './use-planner-document-persistence';
import { usePlannerPageAssetInteractions } from './use-planner-page-asset-interactions';
import { usePlannerPageBaseState } from './use-planner-page-base-state';
import { usePlannerPageContentInteractions } from './use-planner-page-content-interactions';
import { usePlannerPageModelState } from './use-planner-page-model-state';
import { usePlannerPageRunLifecycle } from './use-planner-page-run-lifecycle';
import { usePlannerPageSectionState } from './use-planner-page-section-state';
import { usePlannerRuntimeWorkspace } from './use-planner-runtime-workspace';
import { usePlannerStream } from './use-planner-stream';

export interface UsePlannerPageStateOptions {
  studio: PlannerPageData;
  runtimeApi?: PlannerRuntimeApiContext;
  initialGeneratedText?: string | null;
  initialStructuredDoc?: PlannerStructuredDoc | null;
  initialPlannerReady?: boolean;
  initialWorkspace?: ApiPlannerWorkspace | null;
}

export function usePlannerPageState(options: UsePlannerPageStateOptions) {
  const {
    studio,
    runtimeApi,
    initialGeneratedText,
    initialStructuredDoc,
    initialPlannerReady,
    initialWorkspace,
  } = options;

  const router = useRouter();
  const baseState = usePlannerPageBaseState({
    studio,
    initialGeneratedText,
    initialStructuredDoc,
    initialWorkspace,
  });
  const {
    subjectUploadInputRef,
    sceneUploadInputRef,
    activeEpisodeId,
    setActiveEpisodeId,
    displayTitle,
    setDisplayTitle,
    aspectRatio,
    setAspectRatio,
    storyboardModelId,
    setStoryboardModelId,
    remainingPoints,
    requirement,
    setRequirement,
    notice,
    setNotice,
    outlineConfirmed,
    setOutlineConfirmed,
    historyMenuOpen,
    setHistoryMenuOpen,
    runtimeWorkspace,
    setRuntimeWorkspace,
    messages,
    setMessages,
    plannerImageAssets,
    setPlannerImageAssets,
    assetUploadPending,
    setAssetUploadPending,
    serverPlannerText,
    setServerPlannerText,
    structuredPlannerDoc,
    setStructuredPlannerDoc,
    plannerSubmitting,
    setPlannerSubmitting,
  } = baseState;

  const { streamState, startPlannerStream, stopPlannerStream } = usePlannerStream(runtimeApi);
  const modelState = usePlannerPageModelState({
    studio,
    runtimeApi,
    runtimeWorkspace,
    initialGeneratedText,
    initialPlannerReady,
    structuredPlannerDoc,
    activeEpisodeId,
    setActiveEpisodeId,
    displayTitle,
    storyboardModelId,
    aspectRatio,
    setOutlineConfirmed,
    router,
    streamSteps: streamState?.steps.length ? streamState.steps : (runtimeWorkspace?.activeRefinement?.stepAnalysis ?? []),
  });
  const { plannerMode, plannerDoc, refinement, runtimeState, displayState, pointCost, mediaCardStyle } = modelState;
  const runtimeActiveOutline = runtimeState.runtimeActiveOutline;
  const runtimeActiveRefinement = runtimeState.runtimeActiveRefinement;
  const latestPlannerExecutionMode = runtimeState.latestPlannerExecutionMode;
  const {
    plannerEpisodes,
    activeEpisode,
    activeStyle,
    activeEpisodeNumber,
    usingRuntimePlanner,
    displaySubjectCards,
    displaySceneCards,
    displayScriptActs,
    displaySections,
    displayVersionStatus,
    displayVersionProgress,
    selectedStoryboardModel,
    shotTitleById,
    historyVersions,
    historyActiveVersionId,
    hasDisplayVersion,
    refinementDetailSteps,
  } = displayState;

  const { refreshPlannerWorkspace, ensureEditableRuntimeRefinement, activateHistoryVersion } = usePlannerRuntimeWorkspace({
    runtimeApi,
    runtimeWorkspace,
    runtimeActiveRefinement,
    setRuntimeWorkspace,
    setPlannerImageAssets: (assets) => setPlannerImageAssets(assets),
    setDisplayTitle,
    setMessages,
    setServerPlannerText,
    setStructuredPlannerDoc,
    setOutlineConfirmed,
    setNotice,
    mapWorkspaceMessagesToThread,
    outlineToPreviewStructuredPlannerDoc: runtimeState.outlineToPreviewStructuredPlannerDoc,
  });

  const { saveState, persistPlannerDoc } = usePlannerDocumentPersistence({
    runtimeApi,
    ensureEditableRuntimeRefinement,
    setStructuredPlannerDoc,
    setNotice,
  });

  const { submitPlannerRunViaApi, submitPartialRerunViaApi, submitPlannerImageGenerationViaApi } = usePlannerPageRunLifecycle({
    runtimeApi,
    refreshPlannerWorkspace,
    startPlannerStream,
    stopPlannerStream,
    setPlannerSubmitting,
    setServerPlannerText,
    setStructuredPlannerDoc,
    setOutlineConfirmed,
    setMessages,
    setNotice,
    hydrateReadyVersion: refinement.hydrateReadyVersion,
    selectVersion: refinement.selectVersion,
  });

  const {
    assetDrafts,
    dialogDisplayState,
    assetActions,
  } = usePlannerPageAssetInteractions({
    runtimeApi,
    runtimeWorkspace,
    runtimeActiveRefinement,
    plannerDoc,
    structuredPlannerDoc,
    displaySubjectCards,
    displaySceneCards,
    plannerImageAssets,
    subjectUploadInputRef,
    sceneUploadInputRef,
    refreshPlannerWorkspace,
    ensureEditableRuntimeRefinement,
    submitPartialRerunViaApi,
    submitPlannerImageGenerationViaApi,
    persistPlannerDoc,
    updateSubject: refinement.updateSubject,
    updateScene: refinement.updateScene,
    setPlannerImageAssets,
    setAssetUploadPending,
    setPlannerSubmitting,
    setNotice,
  });
  const {
    shotEditor,
    shotPromptPreviewState,
    composerActions,
    shotActions,
    creationFlow,
  } = usePlannerPageContentInteractions({
    router,
    runtimeApi,
    runtimeWorkspace,
    runtimeActiveOutline,
    runtimeActiveRefinement,
    plannerDoc,
    structuredPlannerDoc,
    displayScriptActs,
    displayVersionStatus,
    remainingPoints,
    pointCost,
    storyboardModelId,
    studioProjectId: studio.project.id,
    plannerSubmitting,
    outlineConfirmed,
    requirement,
    refreshPlannerWorkspace,
    ensureEditableRuntimeRefinement,
    submitPlannerRunViaApi,
    submitPartialRerunViaApi,
    submitPlannerImageGenerationViaApi,
    persistPlannerDoc,
    startRefinement: refinement.startRefinement,
    hydrateReadyVersion: refinement.hydrateReadyVersion,
    selectVersion: refinement.selectVersion,
    updateShot: refinement.updateShot,
    deleteShot: refinement.deleteShot,
    setPlannerSubmitting,
    setNotice,
    setHistoryMenuOpen,
    setOutlineConfirmed,
    setMessages,
    nextLocalId,
  });

  return usePlannerPageSectionState({
    shell: {
      runtimeEnabled: Boolean(runtimeApi),
      studio,
      plannerMode,
      displayTitle,
      activeEpisodeId,
      setActiveEpisodeId,
      plannerEpisodes,
      activeEpisodeNumber,
      activeEpisodeTitle: activeEpisode?.title ?? '',
      fallbackEpisodeTitle: plannerDoc.episodeTitle,
      saveState,
      latestExecutionMode: latestPlannerExecutionMode,
      activeDebugApplySource: runtimeState.activeDebugApplySource,
      historyMenuOpen,
      setHistoryMenuOpen,
      historyVersions,
      historyActiveVersionId,
      openDebugRun: runtimeState.openDebugRun,
      activateHistoryVersion,
      usingRuntimePlanner,
      selectVersion: refinement.selectVersion,
      setNotice,
      openAgentDebug: runtimeState.openAgentDebug,
      backToExplore: runtimeState.backToExplore,
    },
    thread: {
      studio,
      usingRuntimePlanner,
      messages,
      requirement,
      setRequirement,
      outlineConfirmed,
      runtimeActiveOutline,
      runtimeActiveRefinement,
      plannerSubmitting,
      serverPlannerText,
      refinementDetailSteps,
      activeVersion: refinement.activeVersion,
      activeDebugApplySource: runtimeState.activeDebugApplySource,
      notice,
      openDebugRun: runtimeState.openDebugRun,
      handleComposerSubmit: composerActions.handleComposerSubmit,
      handleConfirmOutline: composerActions.handleConfirmOutline,
    },
    document: {
      hasDisplayVersion,
      runtimeActiveOutline,
      runtimeActiveRefinement,
      displayVersionStatus,
      displayVersionProgress,
      displaySections,
      plannerDoc,
      activeStyle,
      mediaCardStyle,
      displaySubjectCards,
      openSubjectAdjustDialog: assetDrafts.openSubjectAdjustDialog,
      displaySceneCards,
      openSceneAdjustDialog: assetDrafts.openSceneAdjustDialog,
      displayScriptActs,
      plannerSubmitting,
      runtimeEnabled: Boolean(runtimeApi),
      editingShot: shotEditor.editingShot,
      shotDraft: shotEditor.shotDraft,
      openShotInlineEditor: shotEditor.openShotInlineEditor,
      openShotDeleteDialog: shotEditor.openShotDeleteDialog,
      rerunActAdjust: shotActions.rerunActAdjust,
      setShotDraft: shotEditor.setShotDraft,
      rerunShotAdjust: shotActions.rerunShotAdjust,
      generateShotImage: shotActions.generateShotImage,
      cancelShotInlineEditor: shotEditor.cancelShotInlineEditor,
      applyShotInlineEditor: shotActions.applyShotInlineEditor,
      shotPromptPreview: shotPromptPreviewState.shotPromptPreview,
      shotPromptPreviewLoading: shotPromptPreviewState.shotPromptPreviewLoading,
      shotPromptPreviewError: shotPromptPreviewState.shotPromptPreviewError,
      selectedStoryboardModel,
      storyboardModelId,
      setStoryboardModelId,
      aspectRatio,
      setAspectRatio,
      startCreation: creationFlow.startCreation,
      creationActionLabel: creationFlow.creationActionLabel,
      creationActionDisabled: creationFlow.creationActionDisabled,
      shotTitleById,
    },
    dialogs: {
      plannerSubmitting,
      runtimeEnabled: Boolean(runtimeApi),
      assetUploadPending,
      booting: creationFlow.booting,
      bootProgress: creationFlow.bootProgress,
      remainingPoints,
      subjectDialogCardId: assetDrafts.subjectDialogCardId,
      activeSubjectCard: dialogDisplayState.activeSubjectCard,
      subjectImageDraft: assetDrafts.subjectImageDraft,
      subjectNameDraft: assetDrafts.subjectNameDraft,
      subjectPromptDraft: assetDrafts.subjectPromptDraft,
      subjectAdjustMode: assetDrafts.subjectAdjustMode,
      activeSubjectAssetLabel: dialogDisplayState.activeSubjectAssetLabel ?? '',
      subjectAssetThumbs: dialogDisplayState.subjectAssetThumbs,
      subjectAssetDraftId: assetDrafts.subjectAssetDraftId,
      subjectRecommendations: assetActions.subjectRecommendations,
      subjectRecommendationsLoading: assetActions.subjectRecommendationsLoading,
      subjectUploadInputRef,
      closeSubjectAdjustDialog: assetDrafts.closeSubjectAdjustDialog,
      setSubjectImageDraft: assetDrafts.setSubjectImageDraft,
      setSubjectAssetDraftId: assetDrafts.setSubjectAssetDraftId,
      setSubjectPromptDraft: assetDrafts.setSubjectPromptDraft,
      setSubjectAdjustMode: assetDrafts.setSubjectAdjustMode,
      applySubjectRecommendation: assetActions.applySubjectRecommendation,
      generateSubjectImage: assetActions.generateSubjectImage,
      rerunSubjectAdjust: assetActions.rerunSubjectAdjust,
      applySubjectAdjust: assetActions.applySubjectAdjust,
      handleSubjectUpload: assetActions.handleSubjectUpload,
      sceneDialogCardId: assetDrafts.sceneDialogCardId,
      activeSceneCard: dialogDisplayState.activeSceneCard,
      sceneImageDraft: assetDrafts.sceneImageDraft,
      sceneNameDraft: assetDrafts.sceneNameDraft,
      scenePromptDraft: assetDrafts.scenePromptDraft,
      sceneAdjustMode: assetDrafts.sceneAdjustMode,
      activeSceneAssetLabel: dialogDisplayState.activeSceneAssetLabel ?? '',
      sceneAssetThumbs: dialogDisplayState.sceneAssetThumbs,
      sceneAssetDraftId: assetDrafts.sceneAssetDraftId,
      sceneRecommendations: assetActions.sceneRecommendations,
      sceneRecommendationsLoading: assetActions.sceneRecommendationsLoading,
      sceneUploadInputRef,
      closeSceneAdjustDialog: assetDrafts.closeSceneAdjustDialog,
      setSceneImageDraft: assetDrafts.setSceneImageDraft,
      setSceneAssetDraftId: assetDrafts.setSceneAssetDraftId,
      setScenePromptDraft: assetDrafts.setScenePromptDraft,
      setSceneAdjustMode: assetDrafts.setSceneAdjustMode,
      applySceneRecommendation: assetActions.applySceneRecommendation,
      generateSceneImage: assetActions.generateSceneImage,
      rerunSceneAdjust: assetActions.rerunSceneAdjust,
      applySceneAdjust: assetActions.applySceneAdjust,
      handleSceneUpload: assetActions.handleSceneUpload,
      shotDeleteDialog: shotEditor.shotDeleteDialog,
      deletingShot: shotEditor.deletingShot,
      closeShotDeleteDialog: shotEditor.closeShotDeleteDialog,
      confirmDeleteShot: shotActions.confirmDeleteShot,
    },
  });
}

export type UsePlannerPageStateResult = ReturnType<typeof usePlannerPageState>;
